-- Run through Alembic or psql before deploying. PostGIS may be added later for route analytics.
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email varchar(320) NOT NULL UNIQUE, password_hash varchar(255) NOT NULL, consent_version varchar(32), consented_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE trips (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), status varchar(16) NOT NULL DEFAULT 'active', started_at timestamptz NOT NULL DEFAULT now(), ended_at timestamptz, distance_m double precision NOT NULL DEFAULT 0, score integer, score_explanation jsonb NOT NULL DEFAULT '{}'::jsonb, model_version varchar(64) NOT NULL DEFAULT 'rules-v1');
CREATE INDEX trips_user_id_idx ON trips(user_id);
CREATE TABLE telemetry_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), trip_id uuid NOT NULL REFERENCES trips(id), client_event_id varchar(64) NOT NULL, occurred_at timestamptz NOT NULL, received_at timestamptz NOT NULL DEFAULT now(), latitude double precision, longitude double precision, speed_mps double precision, accuracy_m double precision, acceleration_g double precision, event_type varchar(32) NOT NULL DEFAULT 'sample', payload jsonb NOT NULL DEFAULT '{}'::jsonb, CONSTRAINT uq_telemetry_idempotency UNIQUE(trip_id, client_event_id));
CREATE INDEX telemetry_events_trip_time_idx ON telemetry_events(trip_id, occurred_at);
CREATE TABLE safety_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), trip_id uuid NOT NULL REFERENCES trips(id), kind varchar(48) NOT NULL, severity varchar(16) NOT NULL, confidence double precision NOT NULL, details jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE wallet_ledger (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), points integer NOT NULL, reason text NOT NULL, idempotency_key varchar(128) NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
