import { FormEvent, useState } from 'react';
import { api, setAccessToken } from '../../lib/api';

type Token = { access_token: string };
export function AuthGate({ onAuthenticated }: { onAuthenticated: () => void }) {
  const [mode, setMode] = useState<'login' | 'register'>('login'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [consent, setConsent] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); if (mode === 'register' && !consent) return setError('Location and telemetry consent is required to create a driving account.'); setBusy(true); try { const token = await api<Token>(`/auth/${mode === 'login' ? 'login' : 'register'}`, { method: 'POST', authenticated: false, body: JSON.stringify(mode === 'login' ? { email, password } : { email, password, consent_version: '2026-09' }) }); setAccessToken(token.access_token); onAuthenticated(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to continue'); } finally { setBusy(false); } };
  return <main className="min-h-[100dvh] grid place-items-center bg-slate-950 p-5 text-slate-900"><form onSubmit={submit} className="w-full max-w-sm rounded-3xl bg-white p-7 shadow-2xl space-y-4"><div><p className="text-emerald-700 text-xs font-bold tracking-widest">SAFEDRIVE</p><h1 className="mt-1 text-2xl font-black">{mode === 'login' ? 'Welcome back' : 'Create your account'}</h1><p className="mt-2 text-sm text-slate-600">Your trip data is used only with your explicit consent.</p></div><label className="block text-sm font-semibold">Email<input className="mt-1 w-full rounded-xl border p-3" type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label className="block text-sm font-semibold">Password<input className="mt-1 w-full rounded-xl border p-3" type="password" minLength={12} value={password} onChange={e => setPassword(e.target.value)} required /></label>{mode === 'register' && <label className="flex gap-2 text-xs text-slate-600"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} />I consent to location and motion telemetry for recorded trips. I can revoke consent in settings.</label>}{error && <p role="alert" className="text-sm text-rose-700">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-emerald-600 p-3 font-bold text-white disabled:opacity-50">{busy ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create account'}</button><button type="button" onClick={() => setMode(mode === 'login' ? 'register' : 'login')} className="w-full text-sm text-emerald-700">{mode === 'login' ? 'New to SafeDrive? Create an account' : 'Already have an account? Sign in'}</button></form></main>;
}
